# Generated by Django 6.0.5 on 2026-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='free_first_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='lesson_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='online_platforms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='students_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='teaching_methods',
            field=models.TextField(blank=True),
        ),
    ]
